### ISSUE TITLE
how this code constraints FLOPs?

### ISSUE THREAD

**Issue by cingyoung** [zhengxiawu/MIGO_NAS#1]
thank you for sharing your code!
i've read your code many times to understanding the 'mobile setting' code.
but i can't exactly understand how '<get_path> definition code' can constraint FLOPs?

and what is dp? dp is just a flops table? then how it works on constraint?

https://github.com/zhengxiawu/MIGO_NAS/blob/d6ceb1e120586011897b76ffc39a3d9532ac86dd/network_generator.py#L212

i really appreciate for your answer in advance!

**Comment by zhengxiawu** [comment]
1. dp =  dynamic programming.
2. Our paper will be available soon.
3. Basically, the method consider the distribution as a utility function, and consider the FLOPs as a "weight". In this way, we can transform the problem to a packing problem.
4. All the codes have moved to https://github.com/MAC-AutoML/XNAS. Unfortunately, we are now writing papers for ICCV and NeulPS. And the code maybe not very friendly to use. But we will do our best as soon as possible:)

**Comment by cingyoung** [comment]
thank you! i'll wait for your great paper to further understand your code and idea
