### ISSUE TITLE
Why the final precision is only around 70%?

### ISSUE THREAD

**Issue by suo98** [zhengxiawu/MIGO_NAS#2]
Thank you for sharing your code. I've run MIGO-NAS on CIFAR-10 with ofa and darts search space.  Why the final precision is only around 70% but the precision of top5 is much more higher?

**Comment by zhengxiawu** [comment]
Thanks for your attention. The code is now moving to https://github.com/MAC-AutoML/XNAS. In the repo we provide a detailed experimental result and will be continue updating.

**Comment by zhengxiawu** [comment]
In addition, what we provide is only search code. In other words, after the search is finished, you need to put the searched network architecture into another repo for training. For example, when searching in the darts search space, you need to copy the searched genotype to https://github.com/khanrc/pt.darts  to get the final result.

**Comment by suo98** [comment]
Thanks a lot for your patience!
